#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


FILES=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$FILES" ]; then
  exit 0
fi

SRC_FILES=$(echo "$FILES" | grep -E '(src|include)/.+\.(hpp|cpp|h|cxx|hxx|c|inl)$' || true)

if ! [ -z "$SRC_FILES" ]; then
  echo "$SRC_FILES" | xargs clang-format -i
fi

echo "$FILES" | xargs git add

exit 0
